; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Heeba"
#define MyAppVersion "1.6"
#define MyAppExeName "heeba.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{B1BC06DB-2B18-4D67-8880-939FB2CD97CA}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
DefaultDirName={autopf}\{#MyAppName}
DisableDirPage=yes
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=C:\Users\kavim\Downloads\Heeba\InnoCompiler\license.txt
InfoBeforeFile=C:\Users\kavim\Downloads\Heeba\InnoCompiler\BeforeInstallation.txt
InfoAfterFile=C:\Users\kavim\Downloads\Heeba\InnoCompiler\AfterInstallation.txt
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputDir=C:\Users\kavim\Downloads\Heeba\InnoCompiler
OutputBaseFilename=HeebaInstaller
SetupIconFile=C:\Users\kavim\Downloads\Heeba\InnoCompiler\heeba.ico
SolidCompression=yes
WizardStyle=modern

[Environment]
UserPathVar=Path;{app}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "C:\Users\kavim\Downloads\Heeba\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kavim\Downloads\Heeba\dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
;Registry data from file heeba.reg
Root: HKCU; Subkey: "Environment"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Environment"; ValueType: string; ValueName: "HeebaPath"; ValueData: "C:\Program Files\Heeba"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Environment"; ValueType: string; ValueName: "HeebaVersion"; ValueData: "1.3.0"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\.heeba"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\.heeba"; ValueType: string; ValueName: ""; ValueData: "Heeba.SessionFile"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\.heeba"; ValueType: string; ValueName: "Content Type"; ValueData: "application/json"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\Heeba.SessionFile"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Heeba.SessionFile"; ValueType: string; ValueName: ""; ValueData: "Heeba Session File"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\Heeba.SessionFile\DefaultIcon"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Heeba.SessionFile\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "C:\Program Files\Heeba\heeba.exe,0"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\Heeba.SessionFile\shell"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Heeba.SessionFile\shell\open"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Heeba.SessionFile\shell\open"; ValueType: string; ValueName: ""; ValueData: "Open with Heeba"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\Heeba.SessionFile\shell\open\command"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Heeba.SessionFile\shell\open\command"; ValueType: string; ValueName: ""; ValueData: "\""C:\Program Files\Heeba\heeba.exe\"" \""--session\"" \""%1\"""; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\heeba"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\heeba"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\heeba"; ValueType: string; ValueName: ""; ValueData: "URL:Heeba Protocol"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\heeba"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\heeba\DefaultIcon"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\heeba\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "C:\Program Files\Heeba\heeba.exe,0"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\heeba\shell"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\heeba\shell\open"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\heeba\shell\open"; ValueType: string; ValueName: ""; ValueData: "Open with Heeba"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\heeba\shell\open\command"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\heeba\shell\open\command"; ValueType: string; ValueName: ""; ValueData: "\""C:\Program Files\Heeba\heeba.exe\"" \""%1\"""; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\heeba.exe"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\heeba.exe"; ValueType: string; ValueName: ""; ValueData: "Heeba - Personal AI Terminal Companion"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\heeba.exe\DefaultIcon"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\heeba.exe\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "C:\Program Files\Heeba\heeba.exe,0"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\heeba.exe\shell"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\heeba.exe\shell\open"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\heeba.exe\shell\open"; ValueType: string; ValueName: ""; ValueData: "Run Heeba"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\heeba.exe\shell\open\command"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\heeba.exe\shell\open\command"; ValueType: string; ValueName: ""; ValueData: "\""C:\Program Files\Heeba\heeba.exe\"""; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Heeba"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Heeba\Settings"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Heeba\Settings"; ValueType: string; ValueName: "InstallPath"; ValueData: "C:\Program Files\Heeba"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Heeba\Settings"; ValueType: string; ValueName: "Version"; ValueData: "1.3.0"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Heeba\Settings"; ValueType: string; ValueName: "InstallDate"; ValueData: ""; Flags: uninsdeletevalue
;End of registry data from file heeba.reg

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

